# Generated by Django 4.2.14 on 2024-07-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_farm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/farm_logos/', verbose_name='farm logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pictures/', verbose_name='profile picture'),
        ),
    ]
