# Generated by Django 4.2.14 on 2024-09-02 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_farm_farm_logo_alter_user_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeding_date', models.DateField()),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('number_of_offspring', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.CharField(choices=[('Cow', 'Cow'), ('Sheep', 'Sheep'), ('Pig', 'Pig')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('acquisition_date', models.DateField()),
                ('acquisition_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Deceased', 'Deceased')], max_length=10)),
                ('current_weight', models.FloatField()),
                ('current_age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livestock_photos/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.farm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_weight', models.FloatField()),
                ('birth_order', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('breeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.breedingrecord')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring_record', to='management.livestock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('Illness', 'Illness'), ('Vaccination', 'Vaccination'), ('Routine Check', 'Routine Check')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medication', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.livestock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('feeding_date', models.DateField()),
                ('feeding_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.livestock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_father', to='management.livestock'),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_mother', to='management.livestock'),
        ),
    ]
