# Generated by Django 4.2.14 on 2024-09-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='acquisition_method',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Gift', 'Gift'), ('Trade', 'Trade'), ('Breeding', 'Breeding'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='animal_type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Sheep', 'Sheep'), ('Pig', 'Pig'), ('Goat', 'Goat'), ('Horse', 'Horse'), ('Chicken', 'Chicken'), ('Duck', 'Duck'), ('Turkey', 'Turkey'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='tag_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
