# Generated by Django 4.2.14 on 2024-09-02 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_livestock_acquisition_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='feeding_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='feeding_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
