# Generated by Django 4.2.14 on 2024-09-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_feedingrecord_feeding_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='feeding_date',
        ),
        migrations.RemoveField(
            model_name='feedingrecord',
            name='feeding_time',
        ),
    ]
