# Generated by Django 4.2.14 on 2024-09-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_feedingrecord_feeding_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offspring',
            name='breeding_record',
        ),
        migrations.RemoveField(
            model_name='offspring',
            name='livestock',
        ),
        migrations.DeleteModel(
            name='BreedingRecord',
        ),
        migrations.DeleteModel(
            name='Offspring',
        ),
    ]
